version: '3'
services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile

    image: alejandroe96/wiki-game-app:${APP_VERSION}

    container_name: wiki-game
    ports:
      - 3000:3000
    environment:
      - APP_VERSION=${APP_VERSION}
      - STAGE=${STAGE}
      - PORT=${PORT}
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}